// localStorage keys
export const STORAGE_KEYS = {
  PROMPT: "mintai:prompt",
  STYLE: "mintai:style",
  GENERATED_IMAGES: "mintai:generated",
  MINTED_NFTS: "mintai:minted-nfts",
} as const;

// Generation limits
export const GENERATION = {
  MIN_COUNT: 1,
  MAX_COUNT: 10,
  MAX_REFERENCE_IMAGE_SIZE: 5 * 1024 * 1024, // 5MB
  ALLOWED_IMAGE_TYPES: ["image/png", "image/jpeg", "image/webp", "image/gif"],
  ALLOWED_STYLES: [
    "none",
    "anime",
    "digital-art",
    "pixel-art",
    "watercolor",
    "3d-render",
    "oil-painting",
    "cyberpunk",
    "fantasy",
    "pop-art",
    "surrealism",
    "impressionism",
    "sketch",
    "vaporwave",
    "noir",
    "minimalist",
    "stained-glass",
    "ukiyo-e",
    "comic-book",
    "low-poly",
    "steampunk",
    "art-deco",
    "graffiti",
    "glitch-art",
    "isometric",
  ],
} as const;

export const STYLE_PROMPTS: Record<string, string> = {
  anime: "in anime art style, detailed anime illustration",
  "digital-art": "digital art, highly detailed digital illustration",
  "pixel-art": "pixel art style, retro pixel art",
  watercolor: "watercolor painting style, soft watercolor illustration",
  "3d-render": "3D rendered, photorealistic 3D illustration, octane render",
  "oil-painting": "oil painting style, classical oil painting technique",
  cyberpunk: "cyberpunk style, neon lights, futuristic cyberpunk aesthetic",
  fantasy: "fantasy art style, epic fantasy illustration, magical",
  "pop-art": "pop art style, bold colors, Ben-Day dots, Roy Lichtenstein inspired",
  surrealism: "surrealist art style, dreamlike, Salvador Dalí inspired, impossible geometry",
  impressionism: "impressionist painting, visible brushstrokes, soft light, Monet inspired",
  sketch: "pencil sketch style, hand-drawn, detailed graphite illustration",
  vaporwave: "vaporwave aesthetic, retro 80s, pastel neon, glitch, Roman busts",
  noir: "film noir style, high contrast black and white, dramatic shadows, moody",
  minimalist: "minimalist art style, clean lines, simple shapes, limited color palette",
  "stained-glass": "stained glass art style, vibrant translucent colors, bold black outlines",
  "ukiyo-e": "ukiyo-e Japanese woodblock print style, Hokusai inspired, flat colors",
  "comic-book": "comic book art style, bold ink outlines, halftone shading, vibrant panels",
  "low-poly": "low-poly 3D art style, geometric facets, minimal polygons, stylized",
  steampunk: "steampunk style, Victorian industrial, brass gears, clockwork machinery",
  "art-deco": "art deco style, geometric patterns, gold and black, 1920s glamour",
  graffiti: "street art graffiti style, spray paint, urban, bold colors, stencil art",
  "glitch-art": "glitch art style, digital distortion, pixel sorting, RGB shift, databending",
  isometric: "isometric pixel art, 3D isometric view, detailed miniature scene",
};
